### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by vany0114** [aelij/vsts-service-fabric#6]
Hi, does it support deployments with Docker images? I'm not even sure if that is possible...how to compare the content of the images? One of the things I come up with is avoiding to build a new version of the image if the code doesn't change at all, so like that the image version will be the same and I can aware that there are no changes thru the image version, but how to do that?

**Comment by aelij** [comment]
No, I don't see how Docker images would be supported with this extension.

However, since Docker itself uses hashing when building images, you might be able to achieve a similar effect by applying the Docker hash to the SF code package version (I haven't tried this, just guessing).

Might be worth asking this in https://github.com/Microsoft/service-fabric.
